# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_edit_widget(object):
    def setupUi(self, edit_widget):
        edit_widget.setObjectName("edit_widget")
        edit_widget.resize(935, 600)
        self.groupBox_2 = QtWidgets.QGroupBox(edit_widget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 160, 331, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.level_1 = QtWidgets.QSlider(self.groupBox_2)
        self.level_1.setGeometry(QtCore.QRect(10, 40, 311, 16))
        self.level_1.setMinimum(1)
        self.level_1.setMaximum(100)
        self.level_1.setProperty("value", 1)
        self.level_1.setOrientation(QtCore.Qt.Horizontal)
        self.level_1.setObjectName("level_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 311, 16))
        self.label_2.setObjectName("label_2")
        self.level_2 = QtWidgets.QSlider(self.groupBox_2)
        self.level_2.setGeometry(QtCore.QRect(10, 90, 311, 16))
        self.level_2.setMinimum(1)
        self.level_2.setMaximum(100)
        self.level_2.setProperty("value", 1)
        self.level_2.setOrientation(QtCore.Qt.Horizontal)
        self.level_2.setObjectName("level_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 311, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 311, 16))
        self.label_5.setObjectName("label_5")
        self.label_1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_1.setGeometry(QtCore.QRect(10, 20, 311, 16))
        self.label_1.setObjectName("label_1")
        self.level_5 = QtWidgets.QSlider(self.groupBox_2)
        self.level_5.setGeometry(QtCore.QRect(10, 240, 311, 16))
        self.level_5.setMinimum(1)
        self.level_5.setMaximum(100)
        self.level_5.setProperty("value", 1)
        self.level_5.setOrientation(QtCore.Qt.Horizontal)
        self.level_5.setObjectName("level_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 311, 16))
        self.label_4.setObjectName("label_4")
        self.level_3 = QtWidgets.QSlider(self.groupBox_2)
        self.level_3.setGeometry(QtCore.QRect(10, 140, 311, 16))
        self.level_3.setMinimum(1)
        self.level_3.setMaximum(100)
        self.level_3.setProperty("value", 1)
        self.level_3.setOrientation(QtCore.Qt.Horizontal)
        self.level_3.setObjectName("level_3")
        self.level_4 = QtWidgets.QSlider(self.groupBox_2)
        self.level_4.setGeometry(QtCore.QRect(10, 190, 311, 16))
        self.level_4.setMinimum(1)
        self.level_4.setMaximum(100)
        self.level_4.setProperty("value", 1)
        self.level_4.setOrientation(QtCore.Qt.Horizontal)
        self.level_4.setObjectName("level_4")
        self.save_button = QtWidgets.QPushButton(edit_widget)
        self.save_button.setGeometry(QtCore.QRect(560, 450, 75, 23))
        self.save_button.setObjectName("save_button")
        self.load_button = QtWidgets.QPushButton(edit_widget)
        self.load_button.setGeometry(QtCore.QRect(640, 450, 75, 23))
        self.load_button.setObjectName("load_button")
        self.tabWidget = QtWidgets.QTabWidget(edit_widget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 520, 520))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.update_button = QtWidgets.QPushButton(edit_widget)
        self.update_button.setEnabled(False)
        self.update_button.setGeometry(QtCore.QRect(720, 450, 75, 23))
        self.update_button.setObjectName("update_button")

        self.retranslateUi(edit_widget)
        QtCore.QMetaObject.connectSlotsByName(edit_widget)

    def retranslateUi(self, edit_widget):
        _translate = QtCore.QCoreApplication.translate
        edit_widget.setWindowTitle(_translate("edit_widget", "Form"))
        self.groupBox_2.setTitle(_translate("edit_widget", "Features Control Panel"))
        self.label_2.setText(_translate("edit_widget", "Level 2:"))
        self.label_3.setText(_translate("edit_widget", "Level 3:"))
        self.label_5.setText(_translate("edit_widget", "Level 5:"))
        self.label_1.setText(_translate("edit_widget", "Level 1:"))
        self.label_4.setText(_translate("edit_widget", "Level 4:"))
        self.save_button.setText(_translate("edit_widget", "Save"))
        self.load_button.setText(_translate("edit_widget", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("edit_widget", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("edit_widget", "Tab 2"))
        self.update_button.setText(_translate("edit_widget", "Update"))

