wget "https://drive.google.com/uc?export=download&id=1GtLkO4-krpoz31FT83ZVer8C9hfEYBMY" -O ./models/abstract_girl.pth.tar
wget "https://drive.google.com/uc?export=download&id=1HZZRkkCkbAExBMz7NFAOXQbTrsW0thU_" -O ./models/candy.pth.tar
wget "https://drive.google.com/uc?export=download&id=1gmsFQ2dOOwD3quXkpJAEClArZZPiLBsC" -O ./models/cartoon_popart.pth.tar
wget "https://drive.google.com/uc?export=download&id=1QmoXnvifICK4ifuA68aly9HbdEhJvw05" -O ./models/feathers.pth.tar
wget "https://drive.google.com/uc?export=download&id=16ojMQcvdFZDCCatQoqd0tWh6RFBtslJu" -O ./models/lamuse.pth.tar
wget "https://drive.google.com/uc?export=download&id=1fjiX5qDK6R3xO3Cm1LplpGb_NTpZwFC3" -O ./models/matisse_epoch2.pth.tar
wget "https://drive.google.com/uc?export=download&id=13tFFHWD1X4o9UFGc4YdQXR3u159Eykin" -O ./models/mosaic.pth.tar
wget "https://drive.google.com/uc?export=download&id=1Cozyp7m4q6ZDZS8tI4XeazTWrWZ6TMpe" -O ./models/rabbit_watercolor.pth.tar
wget "https://drive.google.com/uc?export=download&id=1oHSTe974rRc0sVYhOPlk-DsYRPDFy3iI" -O ./models/seated_nude.pth.tar
wget "https://drive.google.com/uc?export=download&id=1DStt_6UmCTbx753-KfIGcyC3JQ3td5IR" -O ./models/sketch.pth.tar
wget "https://drive.google.com/uc?export=download&id=1F9fFbQq0Qrr5K_UxLVM3dTLOZiw6Yw5R" -O ./models/udnie.pth.tar
